name = 'entaq2025'
license = 'No License'
licenselink = ''
description = 'Theme for entaq'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/entaqdev/entaq_site'

# If you have a running demo of the theme
demosite = 'https://entaq.jp'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'hurohukidaikon'
  homepage = 'https://github.com/hurohukidaikon/'
