baseURL = 'https://entaq.jp/'
canonifyURLs = true
categories = ['foo', 'bar', 'baz']
categories_weight = 44
defaultContentLanguage = 'ja'
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
languageCode = 'ja-jp'
[languages]
  [languages.ja]
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
removePathAccents = true
tags = ['hoge', 'fuga', 'poyo']
tags_weight = 22
theme = 'entaq2025'
timeZone = 'Asia/Tokyo'
title = 'entaq'
