description = 'デフォルトの概要文です。'
coverImage = 'images/cover-image.png'
noImage = 'images/no-image.png'
imageResize = "192x webp"

[author]
  name = 'entaq'
  established = '2012'
  zipCode = ''
  country = ''
  address = ''
  googleMapUrl = ''
  tel = ''
  email = ''
  website = ''

[google]
  analytics.id = 'G-3K29NNDRBT'

[facebook]
  app.id = ''

[twitter]
  id = ''
  card = 'summary_large_image'
